# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'operator_search.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(500, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.checkBox_re = QtWidgets.QCheckBox(Dialog)
        self.checkBox_re.setObjectName("checkBox_re")
        self.horizontalLayout.addWidget(self.checkBox_re)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBox_category = QtWidgets.QCheckBox(Dialog)
        self.checkBox_category.setChecked(False)
        self.checkBox_category.setObjectName("checkBox_category")
        self.horizontalLayout_2.addWidget(self.checkBox_category)
        self.checkBox_name = QtWidgets.QCheckBox(Dialog)
        self.checkBox_name.setChecked(True)
        self.checkBox_name.setObjectName("checkBox_name")
        self.horizontalLayout_2.addWidget(self.checkBox_name)
        self.checkBox_descrption = QtWidgets.QCheckBox(Dialog)
        self.checkBox_descrption.setChecked(True)
        self.checkBox_descrption.setObjectName("checkBox_descrption")
        self.horizontalLayout_2.addWidget(self.checkBox_descrption)
        self.checkBox_idname = QtWidgets.QCheckBox(Dialog)
        self.checkBox_idname.setChecked(True)
        self.checkBox_idname.setObjectName("checkBox_idname")
        self.horizontalLayout_2.addWidget(self.checkBox_idname)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.treeWidget = QtWidgets.QTreeWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget.sizePolicy().hasHeightForWidth())
        self.treeWidget.setSizePolicy(sizePolicy)
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        self.treeWidget.header().setDefaultSectionSize(150)
        self.treeWidget.header().setSortIndicatorShown(True)
        self.verticalLayout.addWidget(self.treeWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Operator Search"))
        self.label.setText(_translate("Dialog", "Filter"))
        self.checkBox_re.setText(_translate("Dialog", "RE"))
        self.checkBox_category.setText(_translate("Dialog", "Category"))
        self.checkBox_name.setText(_translate("Dialog", "Name"))
        self.checkBox_descrption.setText(_translate("Dialog", "Description"))
        self.checkBox_idname.setText(_translate("Dialog", "ID Name"))
        self.treeWidget.setSortingEnabled(True)
        self.treeWidget.headerItem().setText(0, _translate("Dialog", "Category"))
        self.treeWidget.headerItem().setText(1, _translate("Dialog", "Name"))
        self.treeWidget.headerItem().setText(2, _translate("Dialog", "Description"))
        self.treeWidget.headerItem().setText(3, _translate("Dialog", "ID Name"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("Dialog", "WindowManager"))
        self.treeWidget.topLevelItem(0).setText(1, _translate("Dialog", "Splash Screen"))
        self.treeWidget.topLevelItem(0).setText(2, _translate("Dialog", "Display splash"))
        self.treeWidget.topLevelItem(0).setText(3, _translate("Dialog", "wm.splash"))
        self.treeWidget.topLevelItem(1).setText(0, _translate("Dialog", "Transform"))
        self.treeWidget.topLevelItem(1).setText(1, _translate("Dialog", "Translate"))
        self.treeWidget.topLevelItem(1).setText(3, _translate("Dialog", "transform.translate"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)

